### ISSUE TITLE
Pass a wrong argument, `story_size` and `sentence_size`

### ISSUE THREAD

**Issue by jojonki** [siyuanzhao/key-value-memory-networks#12]
I found your code passes wrong argument for `story_size`. You passed `sentence_size` to `story_size` argument. In my understanding, `sentence_size` is a longest sentence, i.e. the number of words in a sentence, and `story_size` is a longest history, i.e. the number of history sentences.

Then, I think you also have to modify a code of `position_encoding` because it also use `story_size` as `sentence_size`.
https://github.com/siyuanzhao/key-value-memory-networks/blob/master/key_value_memory/single.py#L96
https://github.com/siyuanzhao/key-value-memory-networks/blob/master/key_value_memory/memn2n_kv.py#L97

**Comment by siyuanzhao** [comment]
story_size is the longest length of the sentences in a story, not the number of sentences in a story.
The number of sentences determines the size of the memory.

position_encoding needs the length of the sentence in order to work.

**Comment by jojonki** [comment]
@siyuanzhao Thank you for your reply.
To be confirm, `max_story_size` is the number of sentences in all history, isn't it? Then, I supposed `story_size` is the number of sentences in a history.

https://github.com/siyuanzhao/key-value-memory-networks/blob/master/key_value_memory/single.py#L46

**Comment by siyuanzhao** [comment]
Right. max_story_size is the number of sentences in a story.

**Comment by jojonki** [comment]
@siyuanzhao Thank you for your confirmation!
