### ISSUE TITLE
Are key and value the same?

### ISSUE THREAD

**Issue by Frankszc** [siyuanzhao/key-value-memory-networks#18]
Hello ,thanks for your implementation.
I have a question.
……………………………………………………………………………………………………………………………………………
        def train_step(s, q, a):
            feed_dict = {
                model._memory_value: s,
                model._query: q,
                model._memory_key: s,
                model._labels: a,
                model.keep_prob: FLAGS.keep_prob
            }
            _, step, predict_op = sess.run([train_op, global_step, model.predict_op], feed_dict)
            return predict_op

        def test_step(s, q):
            feed_dict = {
                model._query: q,
                model._memory_key: s,
                model._memory_value: s,
                model.keep_prob: 1
            }
            preds = sess.run(model.predict_op, feed_dict)
            return preds
……………………………………………………………………………………………………………………………………………
it is in the single.py, so model._memory_value: s, model._memory_key: s, I think they are both story, so  are key and value the same?
Thanks!

**Comment by siyuanzhao** [comment]
yes, key and value are the same.
