### ISSUE TITLE
Improve Python 3 compatibility

### ISSUE THREAD

**Issue by matthias-samwald** [siyuanzhao/key-value-memory-networks#2]
I'm currently trying to get this to run in Python 3, but are running into trouble. The map and reduce functions seem to have been completely overhauled in Python 3, e.g. http://stackoverflow.com/questions/13638898/how-to-use-filter-map-and-reduce-in-python-3

**Comment by siyuanzhao** [comment]
I have no experience on python 3. I will take a look at what I could do about this.

**Comment by matthias-samwald** [comment]
I succeeded in converting to Python 3 via the 2to3 tool and some manual edits. Running single.py with a few different tasks and running joint.py with default settings now worked without errors. I guess I could make the result available via a forked repo of my own? (not sure what the best practice here would be, sorry!). Thanks for the awesome code!

I am getting an error when trying to use the simple_gru reader, but it seems unrelated to the Py2/Py3 conversion. I will look into it and file a separate issue if required.
