### ISSUE TITLE
Tensor dimension mismatch when trying to use simple_gru reader

### ISSUE THREAD

**Issue by matthias-samwald** [siyuanzhao/key-value-memory-networks#4]
"python3 single.py --task_id 1 --reader simple_gru" leads to error message
"ValueError: Dimensions 20 and 30 are not compatible"
"python3 single.py --task_id 1 --reader simple_gru" leads to error message
"ValueError: Dimensions 34 and 30 are not compatible"
"python3 single.py --task_id 4 --reader simple_gru" leads to error message
ValueError: Dimensions 15 and 30 are not compatible

and so on.

"python3 joint.py --reader simple_gru" leads to error message
ValueError: Dimensions 175 and 40 are not compatible

I have tried if changing the feature size parameter changes or partially fixes the error, but the error message stays the same. 

"python3 single.py --task_id 1 --reader simple_gru --feature_size 20" still leads to the same error message
"ValueError: Dimensions 20 and 30 are not compatible"

All these errors are traced to the following line of code in the **init** section of memn2n_kv.py:
`y_tmp = tf.matmul(self.B, self.W_memory, transpose_b=True)`

**Comment by siyuanzhao** [comment]
I updated the code for this mismatch.
simple_gru doesn't outperform bow.

**Comment by matthias-samwald** [comment]
This fixed the bug. Thanks!
