### ISSUE TITLE
What is the difference between KVMem and MemN2N if k=v=sentence?

### ISSUE THREAD

**Issue by lanshuofeng** [siyuanzhao/key-value-memory-networks#6]
I've read this repo and found that 
```python
feed_dict = {
                model._memory_value: s,
                model._query: q,
                model._memory_key: s,
                model._labels: a,
                model.keep_prob: FLAGS.keep_prob
            }
```
so if key = value = sentence,  is this implementation equal to memn2n?

**Comment by siyuanzhao** [comment]
Conceptually, if key==value, key value mem is equal to memn2n.
Mathematically, the computation for each model is slightly different.
Also, you can have a feature mapping for key to calculate the similarity and another feature mapping for value for reading content.
